### ISSUE TITLE
A precompiled nisprog?

### ISSUE THREAD

**Issue by rimwall** [fenugrec/nisprog#19]
Hi again, I noticed on RR that you keep a zip package updated on the forum with the latest precompiled nisprog. I was wondering whether it might be easier to maintain updates by placing a precompiled nisprog in the repo? Saves having to go back and edit the RR post. I have put a precompiled nisprog (with all up-to-date commits) in my branch to save you the trouble, although you may want to do your own compile for the one that goes in your repo?

I have also put an up-to-date pre-compiled ssmk_SH_7055_18.bin in my branch which you may want to pull across. But because I'm not using GitHub desktop it doesn't have the right ID number.

Once this is done, I'd be hoping to tell RR folk to download the 4 specific files in your nisprog/npkern repo (nisprog.exe ssmk_prog.ini and 2 x ssmk_*.bin files), rather than uploading a zip package to RR. Let me know if there is a better way. Thanks.

**Comment by fenugrec** [comment]
I've had enough of people using super old npkern builds and having problems, so packaging a .zip with nisprog and the most recent kernels helps with that. I think it would be better to have as few different sources for builds as possible. Otherwise, same idea - people complain, they don't say where they got the build, and everybody wastes their time.

I should tag a nisprog release soon anyway, there have been many new keys and with this initial subaru support it would be good excuse.

**Comment by fenugrec** [comment]
Just tagged and released 1.05. Available on forum as well as sourceforge with newest kernels (SH****_145-25c5d7d)
